# Generated by Django 5.2 on 2025-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department_en',
            field=models.CharField(max_length=100, null=True, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_en',
            field=models.CharField(max_length=100, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='position'),
        ),
    ]
