# Generated by Django 5.2 on 2025-04-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imported', '0002_alter_importeddata_columns_alter_importeddata_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importeddata',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='importeddata',
            name='rows_count',
        ),
    ]
