# Generated by Django 5.2 on 2025-04-28 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_description_en_file_description_uz_and_more'),
        ('imported', '0003_remove_importeddata_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddata',
            name='source_file_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_data', to='files.file', verbose_name='source file'),
        ),
        migrations.AddField(
            model_name='importeddata',
            name='source_file_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_data', to='files.file', verbose_name='source file'),
        ),
    ]
