# Generated by Django 5.2 on 2025-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imported', '0004_importeddata_source_file_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddata',
            name='columns',
            field=models.JSONField(default=1, verbose_name='columns'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importeddata',
            name='rows_count',
            field=models.PositiveIntegerField(default=0, verbose_name='rows count'),
        ),
    ]
