# Generated by Django 5.2 on 2025-04-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, verbose_name="Ko'rish")),
                ('can_edit', models.BooleanField(default=False, verbose_name='Tahrirlash')),
                ('can_delete', models.BooleanField(default=False, verbose_name="O'chirish")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='files.file', verbose_name='Fayl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Fayl ruxsati',
                'verbose_name_plural': 'Fayl ruxsatlari',
                'unique_together': {('file', 'user')},
            },
        ),
    ]
