# Generated by Django 5.2 on 2025-04-26 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_category_alter_file_description_and_more'),
        ('permission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepermission',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='can delete'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='can edit'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='can_view',
            field=models.BooleanField(default=False, verbose_name='can view'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='files.file', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
