# Generated by Django 5.2 on 2025-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_alter_filepermission_can_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepermission',
            name='can_delete_en',
            field=models.BooleanField(default=False, verbose_name='can delete'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='can_delete_uz',
            field=models.BooleanField(default=False, verbose_name='can delete'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='can_edit_en',
            field=models.BooleanField(default=False, verbose_name='can edit'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='can_edit_uz',
            field=models.BooleanField(default=False, verbose_name='can edit'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='can_view_en',
            field=models.BooleanField(default=False, verbose_name='can view'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='can_view_uz',
            field=models.BooleanField(default=False, verbose_name='can view'),
        ),
    ]
