# Generated by Django 5.2 on 2025-04-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_filepermission_can_delete_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepermission',
            name='can_delete_en',
        ),
        migrations.RemoveField(
            model_name='filepermission',
            name='can_delete_uz',
        ),
        migrations.RemoveField(
            model_name='filepermission',
            name='can_edit_en',
        ),
        migrations.RemoveField(
            model_name='filepermission',
            name='can_edit_uz',
        ),
        migrations.RemoveField(
            model_name='filepermission',
            name='can_view_en',
        ),
        migrations.RemoveField(
            model_name='filepermission',
            name='can_view_uz',
        ),
    ]
