# Generated by Django 5.2 on 2025-04-26 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Yuklash ID')),
                ('file', models.FileField(upload_to='chunked_uploads/', verbose_name='Vaqtinchalik fayl')),
                ('filename', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('offset', models.PositiveIntegerField(default=0, verbose_name='Joriy pozitsiya')),
                ('total_size', models.PositiveIntegerField(verbose_name='Umumiy hajm')),
                ('status', models.CharField(choices=[('uploading', 'Yuklanmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='uploading', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Bo'laklab yuklash",
                'verbose_name_plural': "Bo'laklab yuklashlar",
            },
        ),
    ]
