# Generated by Django 5.2 on 2025-04-26 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunked', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='file',
            field=models.FileField(upload_to='chunked_uploads/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='offset',
            field=models.PositiveIntegerField(default=0, verbose_name='offset'),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='status',
            field=models.CharField(choices=[('uploading', 'Yuklanmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='uploading', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='total_size',
            field=models.PositiveIntegerField(verbose_name='total_size'),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='upload_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='upload id'),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
