# Generated by Django 5.2 on 2025-04-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunked', '0002_alter_chunkedupload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedupload',
            name='filename_en',
            field=models.CharField(max_length=255, null=True, verbose_name='filename'),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='filename_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='filename'),
        ),
    ]
