# Generated by Django 5.2 on 2025-04-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunked', '0003_chunkedupload_filename_en_chunkedupload_filename_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunkedupload',
            name='filename_en',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='filename_uz',
        ),
    ]
