# Generated by Django 5.2 on 2025-04-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('icon', models.CharField(max_length=50, verbose_name='Ikonka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Fayl kategoriyasi',
                'verbose_name_plural': 'Fayl kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('file', models.FileField(upload_to='files/', verbose_name='Fayl')),
                ('file_type', models.CharField(max_length=100, verbose_name='Fayl turi')),
                ('file_size', models.PositiveIntegerField(verbose_name='Fayl hajmi (bayt)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Ommaviy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayllar',
            },
        ),
    ]
